version: '3.9'
services: 
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: development
      MYSQL_USER: giftly
      MYSQL_PASSWORD: pass
      MYSQL_HOST: 'mysql-server'
      MYSQL_PORT: '3309'
    ports:
      - "3309:3306"
    logging:
      driver: none  # Disable logging for mysql


  giftly_groups:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: development
      MYSQL_USER: giftly
      MYSQL_PASSWORD: pass
      MYSQL_HOST: 'mysql-server'
    ports: 
      - 8090:8090
    volumes:
    - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py setup_profile_pic_objects &&
             python manage.py runserver 0.0.0.0:8090"
    depends_on:
      - mysql-server

      


