# Generated by Django 2.2.13 on 2020-07-12 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20200712_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftgroup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
