# Generated by Django 2.2.13 on 2020-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_auto_20200712_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftgroup',
            name='user',
            field=models.ManyToManyField(to='gifts.UserProfile'),
        ),
    ]
