# Generated by Django 2.2.13 on 2020-07-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_auto_20200716_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftgroup',
            name='only_admin_can_invite',
            field=models.BooleanField(default=False),
        ),
    ]
