# Generated by Django 2.2.13 on 2020-07-18 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0010_auto_20200716_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True)),
                ('item_url', models.URLField(blank=True, null=True)),
                ('target_amount', models.FloatField(default=0)),
                ('gift_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.GiftGroup')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorGiftRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.FloatField(default=0)),
                ('has_made_payment', models.BooleanField(default=True)),
                ('payment_has_cleared', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
