# Generated by Django 2.2.13 on 2020-07-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0011_contributorgiftrelation_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='item_title',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='item_url',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='contributorgiftrelation',
            name='gift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='wrap_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.GiftGroup'),
        ),
        migrations.CreateModel(
            name='GiftIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift')),
            ],
        ),
    ]
