# Generated by Django 2.2.13 on 2020-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_auto_20200719_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorgiftrelation',
            name='has_made_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contributorgiftrelation',
            name='payment_has_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
