# Generated by Django 2.2.13 on 2020-07-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0013_auto_20200719_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
