# Generated by Django 2.2.13 on 2020-07-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0014_gift_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='chosen_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_gift', to='gifts.GiftIdea'),
        ),
    ]
