# Generated by Django 2.2.13 on 2020-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0015_gift_chosen_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftgroupinvitation',
            name='days_to_notify',
            field=models.IntegerField(default=14),
        ),
    ]
