# Generated by Django 2.2.13 on 2020-07-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0017_auto_20200720_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_captain', to=settings.AUTH_USER_MODEL),
        ),
    ]
