# Generated by Django 2.2.13 on 2020-07-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0018_gift_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[(1, 'Cheque'), (2, 'Savings')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_branch_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
