# Generated by Django 2.2.13 on 2020-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0019_auto_20200726_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
