# Generated by Django 2.2.13 on 2020-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0020_profile_bank_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Savings', 'Savings')], max_length=20, null=True),
        ),
    ]
