# Generated by Django 2.2.13 on 2020-07-28 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0022_giftidea_suggested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='votes',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
