# Generated by Django 2.2.13 on 2020-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0024_contributorgiftrelation_participation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorgiftrelation',
            name='participation_status',
            field=models.CharField(blank=True, choices=[('approved', 'Yes'), ('rejected', 'No, I am sitting this one out')], default=None, max_length=15, null=True),
        ),
    ]
