# Generated by Django 2.2.13 on 2020-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0026_auto_20200809_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcomment',
            name='content',
            field=models.TextField(),
        ),
    ]
