# Generated by Django 2.2.15 on 2020-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0027_auto_20200809_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftgroup',
            name='icon',
            field=models.CharField(choices=[('fas fa-users', '<i class="fas fa-users"></i>'), ('fas fa-hamburger', '<i class="fas fa-hamburger"></i>'), ('fas fa-gift', '<i class="fas fa-gift"></i>'), ('fas fa-spider', '<i class="fas fa-spider"></i>')], default='fas fa-users', max_length=30),
        ),
    ]
