# Generated by Django 2.2.15 on 2020-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0028_giftgroup_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftgroup',
            name='icon',
            field=models.CharField(choices=[('fas fa-users', 'Group'), ('fab fa-grunt', 'Warthog'), ('fas fa-gift', 'Gift'), ('fab fa-pied-piper-hat', 'Pied Piper'), ('fas fa-user-ninja', 'Ninja'), ('fas fa-dragon', 'Dragon'), ('fas fa-snowman', 'Snowman'), ('fas fa-dog', 'Dog'), ('fas fa-glass-cheers', 'Cheers'), ('fas fa-cat', 'Cat'), ('fas fa-ghost', 'Ghost'), ('fab fa-grav', 'Astronaut')], default='fas fa-users', max_length=30),
        ),
    ]
