# Generated by Django 2.2.15 on 2020-08-17 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0031_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 17, 18, 59, 54, 292472, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='origin',
            field=models.CharField(blank=True, choices=[('patreon', 'Patreon'), ('buy_me_a_coffee', 'Buy Me a Coffee')], max_length=30, null=True),
        ),
    ]
