# Generated by Django 2.2.15 on 2020-08-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0038_groupcommentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.GiftGroup', unique=True)),
            ],
        ),
    ]
