# Generated by Django 2.2.15 on 2020-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0040_auto_20200830_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
