# Generated by Django 2.2.15 on 2020-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0041_gift_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
