# Generated by Django 2.2.15 on 2020-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0042_auto_20200926_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gift_type',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
