# Generated by Django 2.2.15 on 2020-09-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0043_gift_gift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftInvitationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
