# Generated by Django 2.2.15 on 2021-01-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0045_gift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorgiftrelation',
            name='receiver_message',
            field=models.TextField(null=True),
        ),
    ]
