# Generated by Django 3.2.15 on 2023-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0047_contributorgiftrelation_email_notifications_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorgiftrelation',
            name='receiver_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
